# Generated by Django 5.0 on 2026-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
