# Generated by Django 5.0 on 2026-09-18 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gmaps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
